### ISSUE TITLE
Problems with walls

### ISSUE THREAD

**Issue by Lewiscowles1986** [war2/war2edit#34] opened 2017-01-14 10:29 UTC
it seems adding any wall to the very bottom of the map causes the program to crash. It also seems the top-right behaves strangely

**Top Right Issue**  
![top right pictured](https://cloud.githubusercontent.com/assets/2605791/21954269/eadc94ca-da43-11e6-965a-f3bc41ea9954.png)

**Bottom Extents Error**  
```
ERR<13496>:edje lib/edje/edje_calc.c:731 _edje_part_description_apply() Cannot find description "normal" in part "text2" from group "elm/segment_control/item/default". Fallback to default description.
ERR<13496>: /src/war2edit/bin/bitmap.c:1415 _bitmap_full_tile_set() safety check failed: ((unsigned int)x >= ed->pud->map_w) || ((unsigned int)y >= ed->pud->map_h) is true
ERR<13496>:war2edit /src/war2edit/bin/bitmap.c:1496 bitmap_tile_set() Failed to full set a tile
ERR<13496>: /src/war2edit/bin/bitmap.c:1415 _bitmap_full_tile_set() safety check failed: ((unsigned int)x >= ed->pud->map_w) || ((unsigned int)y >= ed->pud->map_h) is true
ERR<13496>:war2edit /src/war2edit/bin/bitmap.c:1496 bitmap_tile_set() Failed to full set a tile
ERR<13496>:eo lib/eo/eo.c:462 _eo_call_resolve() in lib/elementary/elm_widget.eo.c:122: func 'elm_obj_widget_can_focus_get' (419) could not be resolved for class 'Evas_Image'.
ERR<13496>:eo lib/eo/eo.c:462 _eo_call_resolve() in lib/elementary/elm_widget.eo.c:230: func 'elm_obj_widget_child_can_focus_get' (446) could not be resolved for class 'Evas_Image'.
ERR<13496>:eo lib/eo/eo.c:462 _eo_call_resolve() in lib/elementary/elm_widget.eo.c:122: func 'elm_obj_widget_can_focus_get' (419) could not be resolved for class 'Evas_Image'.
ERR<13496>:eo lib/eo/eo.c:462 _eo_call_resolve() in lib/elementary/elm_widget.eo.c:230: func 'elm_obj_widget_child_can_focus_get' (446) could not be resolved for class 'Evas_Image'.
ERR<13496>: /src/war2edit/bin/bitmap.c:1415 _bitmap_full_tile_set() safety check failed: ((unsigned int)x >= ed->pud->map_w) || ((unsigned int)y >= ed->pud->map_h) is true
ERR<13496>:war2edit /src/war2edit/bin/bitmap.c:1496 bitmap_tile_set() Failed to full set a tile
ERR<13496>: /src/war2edit/bin/bitmap.c:1415 _bitmap_full_tile_set() safety check failed: ((unsigned int)x >= ed->pud->map_w) || ((unsigned int)y >= ed->pud->map_h) is true
ERR<13496>:war2edit /src/war2edit/bin/bitmap.c:1496 bitmap_tile_set() Failed to full set a tile
ERR<13496>: /src/war2edit/bin/bitmap.c:1415 _bitmap_full_tile_set() safety check failed: ((unsigned int)x >= ed->pud->map_w) || ((unsigned int)y >= ed->pud->map_h) is true
ERR<13496>:war2edit /src/war2edit/bin/bitmap.c:1496 bitmap_tile_set() Failed to full set a tile
ERR<13496>: /src/war2edit/bin/bitmap.c:1415 _bitmap_full_tile_set() safety check failed: ((unsigned int)x >= ed->pud->map_w) || ((unsigned int)y >= ed->pud->map_h) is true
ERR<13496>:war2edit /src/war2edit/bin/bitmap.c:1496 bitmap_tile_set() Failed to full set a tile
Segmentation fault (core dumped)
```

**Comment by jeanguyomarch** [comment] 2017-01-17 20:51
Hi,

thanks a lot for the report. I could reproduce the crash, and I made a fix for this. I hope it suppress the issues you have encountered -- I couldn't reproduce after the patch.

**Closed as completed** 2017-01-17 20:54 UTC
